language: php

branches:
  only:
    - master
    
matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      env: DEPENDENCIES=beta
    - php: 7.1
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: nightly
      env: SYMFONY_VERSION=^3.0
    - php: nightly
      env: DEPENDENCIES=beta
  allow_failures:
    - php: nightly
      
before_install:
  # Disable xdebug for improved performance; Unstable PHP versions, like nightly, don't have xdebug enabled
  - if [ $(phpenv version-name) != "nightly" ]; then phpenv config-rm xdebug.ini; fi;
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;

before_script: composer install --prefer-dist
script: vendor/bin/phpunit
